### ISSUE TITLE
Saving Frame Changes Image

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#225]
When saving a frame (press 's'), the image filter settings look different, but no filter setting values are changed. This affects the NCC values.  

Also after saving, one Camera seems to lose the Image in the background. But this is inconsistent. 

![preSave](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/3116204f-3cb6-4789-bdab-b5cdcaa762af)
![postSave](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/070e3a64-2610-4ad4-b241-182ae2616268)

**Comment by DajungYoon** [comment]
Version: Autoscoper 2.7.1 -> but crashes when running in SAM

Frame being saved: Attempting to save frame 12

The filter issues are happening in v2.7.1 in only certain key frames (any frame before 24), but the crashing in SAM,  happening in every frame.

**Comment by amymmorton** [comment]
After converting your folder structure to [recommended folder srtucture](https://autoscoper.readthedocs.io/en/latest/tutorials/custom-data.html#recommended-file-structure)

using SAM 5.5.0 pre release 10-25 I was able to replicate the crash when keyframe was attempted on frame 12.



I'm also evaluating #223 , so built in debug
I commented out line 1214 in AutoscoperMainWindow
    //on_actionInsert_Key_triggered(true);
This halted the ncc calculation on initial trial load.

Your tracking data are in column format rather than row- so when loaded in default format- the humerus is not in proper location. (had to load in with col parsing) filters were not inherently loaded. 

Once loaded, navigated in timeline to frame 12, set a breakpoint at 580 in Tracker.cpp

![shol_humQueens](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/6c71472e-188e-4a50-a862-d4b59e472e26)

When I set a keyFrame (s) on frame 12 - the breakpoint is hit via 
![callStackKeyFrame](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/5091713f-a8a3-496f-aede-7621942e9da2)


 ? Does it make sense when we keyFrame to do an ncc calc? Maybe no harm and necessary for downstream setup..
![onkeyS](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/3f7116c1-d695-4c7e-b733-011eb9fe1362)

Either way - the drr is well beyond the bounds of the rad.

When the drr viewport is calculated: in Tracker returns x, y width and height in normalized ccords,

values frame 12
-0.39  -0.10  0.42  0.34 (rounded of course).

results in (unmasked) drr,rad pair:


![drrHumqs](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/a46c1dce-f6ed-44eb-9631-0f9578ced630)
![radQs](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/31e1b55d-273b-4fd9-8b3c-e1794e322779)


I'm kinda surprised you were able to keyframe any of this.. I believe we're darn close to a  drr<->rad mutual clip viewport that will facilitate tracking of data like this.

**Comment by amymmorton** [comment]
@DajungYoon @mjrainbow can yo confirm this issue has been addressed in slicer ver 5.6  SAM PR #230 ?

**Comment by DajungYoon** [comment]
@amymmorton yep, the issue has been resolved using the new version in slicer ver 5.6.
