### ISSUE TITLE
SAM (cuda) crash with mayo shoulder data cfg load

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#241]
as built 12/13/2023 - cuda enabled, 

![callstackCUDA_debug](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/bd9243df-6c11-43c0-bc12-6b529810ded0)
![crash shoulder](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/3e1d1416-101a-4a91-b55a-d4f5e3bdc132)

More details to follow

**Comment by NicerNewerCar** [comment]
The changes I made in #76 resolve this error

**Comment by NicerNewerCar** [comment]
For future reference, this error was caused by the texture reference used to render the radiograph being hardcoded to `unsigned char` datatype, while the array (data read right from the TIFF file) can be set up to be `unsigned char`, `unsigned short`, or `unsigned int`

https://github.com/BrownBiomechanics/Autoscoper/blob/644473784dd0018f5bf8518c5e5322092e4da07d/libautoscoper/src/gpu/cuda/RadRenderer_kernels.cu#L48
https://github.com/BrownBiomechanics/Autoscoper/blob/644473784dd0018f5bf8518c5e5322092e4da07d/libautoscoper/src/gpu/cuda/RadRenderer.cpp#L87-L96
