### ISSUE TITLE
4DCT sequence error

### ISSUE THREAD

**Issue by vforcesar** [BrownBiomechanics/Autoscoper#281]
I tried  to create 4DCT sequences using the 4DCT data as it was loaded, and this is the error I'm getting (See below) . Any ideas on how I can get this working?

![Capture](https://github.com/BrownBiomechanics/Autoscoper/assets/132497790/ba8c72bd-09be-4d57-a8b9-8bb0b32c943c)

@amymmorton

**Comment by amymmorton** [comment]
to add to the issue:
These crashes occurred when attempting to generate VRGs 

We first tried to use the 4dct data node (which showed in the sequences browser and showed a playable volume rendering as toggled) but the  "volume centering transform error'  occurred


We then tried to generate a sequence node from his 4dct volume . When he did so- the available drop down of volumes showed duplicate entries of the sequence . We were able to add the sequence to the browser.
When attemptign to gen vrgs, we chose the second of duplicated seq nodes from the drop down and recieved the 'seq node not belong to this browser node' error.
We switched to the first of duplicate names in the list and recived the index out of range/ centering transfrom error again

**Comment by NicerNewerCar** [comment]
For 4DCT you do not need to need to add anything to a sequence, as Slicer will automatically import true 4DCT as a sequence.

For the "duplicate" volumes, I assume you mean something like this?
![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/a6d5c9ed-f0bf-4184-b9d1-de06b3805cff)

The highlighted volume is the sequence and the volume below that is the "proxy" node (3D volume). For more information about the proxy node see the [Slicer wiki](https://slicer.readthedocs.io/en/latest/user_guide/modules/sequences.html#definitions).

For the "volume centering transform error" I was only able to reproduce when the proxy node was selected.

I think, in order to make this less confusing moving forward, I will segment the input so that for the VRG gen it only allows sequence nodes instead of sequence and volume nodes.

**Comment by amymmorton** [comment]
That sounds like a great plan. Thank you Anthony. Yes.l we were seeing the
proxy node

Cesar- if you still have the scene loaded- can you try the dynamic 4dct
volume mode without the [16] at the end and retry vrg generation?

-----------
Amy Morton, MSc

Sr. Research Engineer, Bioengineering Lab, Department of Orthopaedic
Research
The Warren Alpert Medical School of Brown University and Rhode Island
Hospital
1 Hoppin Street, CORO West, Ste. 404, Providence, RI 02903

**Comment by vforcesar** [comment]
I closed the scene yesterday, but I was able to recreate everything, and it looks like it's working now

![Capture](https://github.com/BrownBiomechanics/Autoscoper/assets/132497790/fcdf76bb-8b32-474b-b969-930519eb07cb)
